apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pvc-cleaner

resources:
  - service-account.yaml
  - cluster-role.yaml
  - cluster-rolebinding.yaml
  - deployment.yaml
  - service.yaml
