apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pvc-cleaner

resources:
  - namespace.yaml
  - service-account.yaml
  - pvc-cleaner-cluster-role.yaml
  - pvc-cleaner-cluster-rolebinding.yaml
  - pvc-cleaner-pod-cluster-role.yaml
  - deployment.yaml
  - service.yaml
