---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvc-cleaner-cluster-role
rules:
- apiGroups:
    - tekton.dev
  resources:
    - pipelineruns
    - pipelineruns/status
  verbs:
    - create
    - get
    - watch
    - delete
    - list
    - patch
- apiGroups:
    - ""
  resources:
    - pods
    - pods/log
    - configmaps
    - namespaces
  verbs:
  - delete
  - deletecollection
  - create
  - patch
  - get
  - list
  - update
  - watch
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - rolebindings
  verbs:
    - get
    - create
    - delete
- apiGroups:
    - ''
  resources:
    - serviceaccounts
  verbs:
    - get
    - create
    - delete
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
  - get
- apiGroups:
    - ""
  resources:
    - persistentvolumeclaims
  verbs:
  - get
  - list
