---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvc-cleaner-role
rules:
- apiGroups:
    - tekton.dev
  resources:
    - taskruns
    - pipelineruns
    - taskruns/status
    - pipelineruns/status
  verbs:
    - create
    - get
    - watch
    - delete
    - list
    - patch
- apiGroups:
    - ""
  resources:
    - pods
    - pods/log
    - configmaps
  verbs:
  - delete
  - deletecollection
  - create
  - patch
  - get
  - list
  - update
  - watch 
